version: '3.9'
services:
  database:
    image: postgres:15
    container_name: wshop_compose_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 333
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wshop_compose_app
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 333
    depends_on:
      - database

volumes:
  postgres_data:
